server:
  port: 8087
spring:
  application:
    name: service-3
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,env