# Development profile shared by all services

# More detailed logging for development
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# Health endpoint details available for everyone in development
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# Development CORS settings - more permissive
cors:
  allowed-origins: "*"

# Enable debug mode for development
debug: true
