# Common configuration shared by all services

# JWT resource server configuration shared by all services
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: '${JWK_SET_URI:http://auth-service:8081/.well-known/jwks.json}'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

# Common Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: '${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka/}'
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Common management endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true

# Common logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

# Common CORS configuration
cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600
