# Production profile shared by all services

# Production logging - more conservative
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: WARN
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Production server optimizations
server:
  tomcat:
    max-threads: 200
    accept-count: 100
    connection-timeout: 20000
  shutdown: graceful

# Restricted management endpoints for production
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# More restrictive CORS for production
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://example.com}
  allow-credentials: true
