# Development profile for messaging-service
server:
  port: 8083
spring:
  application:
    name: messaging-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
