server:
  port: 8761
eureka:
  client:
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
#    registerWithEureka: false
#    fetchRegistry: false
management:
  endpoints:
    web:
      exposure:
        include: health,env
logging:
  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR