server:
  port: 8761

spring:
  application:
    name: discovery-service

# Discovery service specific settings
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

# Override logging for noisy Eureka components
logging:
  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR
