# Production profile for auth-service
# Only includes auth-service specific production settings
# Performance tuning for service-3 in production
tomcat:
  max-threads: 300
  accept-count: 200
  connection-timeout: 30000
# SSL specific configuration for the auth service
server:
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${KEY_STORE:classpath:keystore.p12}
    key-store-password: ${KEY_STORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS:tomcat}

# Auth-service specific logging location
logging:
  file:
    name: /var/log/auth-service/auth-service.log
  level:
    com.example.authservice: INFO

# JWT with longer expiration for production
jwt:
  expiration: 259200  # 3 days in seconds
  refresh-token-expiration: 604800  # 7 days in seconds
