server:
  port: 8085
spring:
  application:
    name: service-1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,env