server:
  port: 8092
spring:
  application:
    name: resilience-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,env